# Generated by Django 5.0.2 on 2024-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('v', 'important'), ('m', 'moins'), ('i', 'Important')], default='i', max_length=1, verbose_name='Task description'),
            preserve_default=False,
        ),
    ]
