# Generated by Django 5.0.2 on 2024-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_name_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='personnel', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.CharField(default='15:42', max_length=65),
            preserve_default=False,
        ),
    ]
